build:
  ci:
    - pwd
#    - rvm use $SHIPPABLE_RUBY
resources:
  - name: guru-www-img
    type: image
    integration: awskey1
    pointer:
      sourceName: "master.1"
    seed:
      versionName: "master.1"
  - name: demo-www-docker-opts
    type: dockerOptions
    versionTemplate:
      memory: 100
      portMappings:
        - 80:80
  - name: demo-www-clus
    type: cluster
    integration: awskey1
    pointer:
      sourceName : "demo"
      region: "us-east-2"


jobs:
  - name: guru_runCI
    type: runCI
    steps:
      - OUT: guru-www-img
  - name: demo-www-man
    type: manifest
    steps:
      - IN: guru-www-img
      - IN: demo-www-docker-opts
        applyTo:
          - demo-guru-img
    flags:
      - Demo
  - name: demo-guru-ecs
    type: deploy
    steps:
     - IN: demo-www-man
     - IN: demo-www-clus
       applyTo:
          - manifest: demo-www-man
            image: guru-www-img
            port: 80
     - TASK: managed
       deployMethod: replace
