build:
  ci:
    - pwd
    - rvm use $SHIPPABLE_RUBY
resources:
  - name: demo-www-img
    type: image
    integration: awskey1
    pointer:
      sourceName: "530443623308.dkr.ecr.us-east-2.amazonaws.com/demo"
    seed:
      versionName: "master.3"
  - name: demo-www-docker-opts
    type: dockerOptions
    versionTemplate:
      memory: 100
      portMappings:
        - 80:80
  - name: demo-www-clus
    type: cluster
    integration: awskey1
    pointer:
      sourceName : "demo-prod"
      region: "us-east-2"


jobs:
  - name: demo_runCI
    type: runCI
    steps:
      - OUT: demo-www-img
  - name: demo-www-man
    type: manifest
    steps:
      - IN: demo-www-img
      - IN: demo-www-docker-opts
        applyTo:
          - services-cram-img
    flags:
      - Demo
  - name: demo-cram-ecs
    type: deploy
    steps:
     - IN: demo-www-man
     - IN: demo-www-clus
       applyTo:
          - manifest: cram-www-man
            image: cram-www-img
            port: 80
     - TASK: managed
       deployMethod: replace
