jobs:
  - name: 22_runCI
    type: runCI
    steps:
      - OUT: demo-www-img

  - name: demo-www-man
    type: manifest
    steps:
      - IN: demo-www-img
      - IN: demo-www-docker-opts
        applyTo:
          - demo-www-img

      - TASK: managed
    flags:
      - Demo

  - name: demo-cram-ecs
    type: deploy
    steps:
     - IN: demo-www-man
     - IN: demo-www-clus
       applyTo:
        - manifest: demo-www-man
          image: demo-www-img
          port: 80
     - TASK: managed
       deployMethod: upgrade
