jobs:
  - name: 22_runCI
    type: runCI
    steps:
      - OUT: demo-www-img

  - name: demo-www-man
    type: manifest
    steps:
      - IN: demo-www-img
      - IN: demo-www-docker-opts
    flags:
      - Demo

  - name: demo-cram-ecs
    type: deploy
    steps:
     - IN: demo-www-man
     - IN: demo-www-clus
     - TASK: managed
       deployMethod: replace
