--- 
jobs:

post_ci: 
  - pwd
  - "rvm use $SHIPPABLE_RUBY" 
  - 
    name: 22_runCI
    steps: 
      - 
        OUT: demo-www-img
    type: runCI
  - 
    flags: 
      - Demo
    name: demo-www-man
    steps: 
      - 
        IN: demo-www-img
      - 
        IN: demo-www-docker-opts
    type: manifest
  - 
    name: demo-cram-ecs
    steps: 
      - 
        IN: demo-www-man
      - 
        IN: demo-www-clus
      - 
        TASK: managed
        deployMethod: replace
    type: deploy

langauge: none



resources: 
  - 
    integration: awskey1
    name: demo-www-img
    pointer: 
      sourceName: 530443623308.dkr.ecr.us-east-2.amazonaws.com/demo
    seed: 
      versionName: master.3
    type: image
  - 
    name: demo-www-docker-opts
    type: dockerOptions
    versionTemplate: 
      memory: 100
      portMappings: 
        - "80:80"
  - 
    integration: awskey1
    name: demo-www-clus
    pointer: 
      region: us-east-2
      sourceName: demo-prod
    type: cluster
